from dotenv import load_dotenv
import os
import anthropic
from datetime import datetime
from menu import (
    clear_screen,
    print_header,
    list_txt_files,
    select_file,
    ask_run_again
)

# -----------------------------------------------
# SETUP
# -----------------------------------------------

load_dotenv()

client = anthropic.Anthropic(
    api_key=os.environ.get("ANTHROPIC_API_KEY")
)

# -----------------------------------------------
# READ A FILE
# -----------------------------------------------

def read_file(filename):
    """Read a text file and return its contents."""
    try:
        with open(filename, "r", encoding="utf-8") as f:
            content = f.read().strip()
        if not content:
            print(f"Error: {filename} is empty. Please add content.")
            exit()
        return content
    except FileNotFoundError:
        print(f"Error: Could not find {filename}.")
        exit()

# -----------------------------------------------
# BUILD THE PROMPT
# -----------------------------------------------

def build_prompt(cv, job_description):
    """Build the analysis prompt."""
    return f"""
You are an expert career coach and recruitment specialist 
with 15 years of experience matching candidates to roles.

You have been given a job description and a candidate's CV. 
Your task is to produce a detailed, honest analysis of how 
well this candidate matches this specific role.

JOB DESCRIPTION:
{job_description}

CANDIDATE CV:
{cv}

Produce your analysis using exactly this structure:

MATCH SCORE
Give an overall match score out of 10. State the score 
on the first line as "Match Score: X/10" then write 
2 sentences explaining what drove that score.

STRONG MATCHES
List every skill, experience, or qualification the 
candidate has that directly matches a requirement in 
the job description. For each one write one sentence 
explaining the match. Minimum 3, maximum 8.

GAPS & MISSING REQUIREMENTS
List every requirement in the job description that 
the candidate's CV does not clearly evidence. For 
each gap write: what is missing, how important it 
appears to be based on the job description, and 
whether it is likely a dealbreaker or something that 
could be addressed in a cover letter.

CV IMPROVEMENT SUGGESTIONS
Give 5 specific, actionable suggestions for improving 
this CV for this specific role. Each suggestion must 
reference something actually in the CV or missing from 
it — no generic advice. Format each as:
CURRENT: what the CV currently says or lacks
SUGGESTED: exactly what to change or add
REASON: why this change improves the match

COVER LETTER ANGLE
Suggest the single strongest angle for this candidate's 
cover letter — the one narrative that makes the best 
case for why they are right for this role despite any 
gaps. Write this as 3 sentences the candidate could 
adapt directly.

HONEST VERDICT
Give a direct, honest overall verdict in 3 sentences. 
Should this candidate apply? What is their realistic 
chance? What is the one thing that would most improve 
their chances?

Tone: direct, specific, and genuinely useful. 
No generic career advice. Every point must be grounded 
in the actual content of the CV and job description 
provided.
"""

# -----------------------------------------------
# RUN THE ANALYSIS
# -----------------------------------------------

def run_analysis(cv_file, jd_file):
    """Run one full CV analysis."""

    # Read the files
    cv = read_file(cv_file)
    job_description = read_file(jd_file)

    # Build and send the prompt
    print("\nAnalysing your CV against the job description...")
    print("Please wait — this takes about 10 seconds...\n")

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=2000,
        messages=[
            {"role": "user", "content": build_prompt(cv, job_description)}
        ]
    )

    analysis = response.content[0].text

    # Print the results
    print("=" * 60)
    print("CV ANALYSIS RESULTS")
    print("=" * 60)
    print(analysis)
    print("=" * 60)

    # Save the results
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    output_filename = f"outputs/analysis_{timestamp}.txt"

    output_content = f"""CV ANALYSIS RESULTS
Generated: {datetime.now().strftime("%d %B %Y at %H:%M")}
{"=" * 60}

CV FILE: {cv_file}
JOB DESCRIPTION FILE: {jd_file}

{"=" * 60}
ANALYSIS
{"=" * 60}

{analysis}

{"=" * 60}
Generated by CV Analyser — built with Anthropic Claude API
"""

    with open(output_filename, "w", encoding="utf-8") as f:
        f.write(output_content)

    print(f"\nAnalysis saved to: {output_filename}")

# -----------------------------------------------
# MAIN LOOP
# -----------------------------------------------

def main():
    """Main program loop."""

    # Make sure outputs folder exists
    os.makedirs("outputs", exist_ok=True)

    run_again = True

    while run_again:
        clear_screen()
        print_header()

        # List available files
        all_txt_files = list_txt_files(
            exclude=["test.py"]
        )

        # Separate CVs and job descriptions
        cv_files = [f for f in all_txt_files if "cv" in f.lower() 
                    or "resume" in f.lower()]
        jd_files = [f for f in all_txt_files if "job" in f.lower() 
                    or "jd" in f.lower() 
                    or "description" in f.lower()
                    or "role" in f.lower()]

        # If no files match the naming patterns show all files
        if not cv_files:
            print("No CV files found — showing all .txt files.\n")
            cv_files = all_txt_files
        if not jd_files:
            print("No job description files found — showing all .txt files.\n")
            jd_files = all_txt_files

        # Let the user choose
        cv_file = select_file(cv_files, "CV")
        jd_file = select_file(jd_files, "job description")

        # Run the analysis
        run_analysis(cv_file, jd_file)

        # Ask if they want to go again
        run_again = ask_run_again()

    print("\nThanks for using CV Analyser. Good luck with your applications!")

# -----------------------------------------------
# RUN THE PROGRAM
# -----------------------------------------------

if __name__ == "__main__":
    main()